### ISSUE TITLE
Check Type of Message

### ISSUE THREAD

**Issue by ghost** [shakibonline/MoonTelegram#7]
Hello,

Add some methods like (isVideo, isAudio, isPhoto and so on) to checking message that is an Image or a Video or ... .

Something like this:
`public function isPhoto() {
      if ($this->message->Photo() != null) {
                     return true;
      }
return false;
}`

Thanks.

**Comment by abbas980301** [comment]
Thanks @MehranAbi. can you do this and send pull request for me?

**Comment by ghost** [comment]
OK, I'll do that.
